[project]
name = "pico-online"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SANIC6", email = "somayajivar@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "numpy>=2.5.2",
    "pygame>=2.6.1",
    "pygame-ce>=2.5.8",
]

[project.scripts]
pico-online = "pico_online:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
